name = "yuque-to-md"
main = "src/index.ts"
compatibility_date = "2024-01-17"

[vars]
DOWNLOAD_IMAGES = "false"

# 如果需要存储大文件，可以配置 R2
# [[r2_buckets]]
# binding = "LAKEBOOK_BUCKET"
# bucket_name = "lakebook-files"
